spring:
  profiles:
    active: ${PROFILE}
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: ${JDBC_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    properties:
      hibernate.dialect: ${DB_DIALECT}
    generate-ddl: true
  ldap:
    urls: ${LDAP_URL}
    base: ${LDAP_BASE}
    username: ${LDAP_USERNAME}
    password: ${LDAP_PASSWORD}
  mail:
    default-encoding: UTF-8
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH}
      mail.smtp.starttls.enable: ${MAIL_SMTP_STARTTLS_ENABLE}
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
        web-admin-password: ${H2_ADMIN_PASSWORD}

server:
  port: ${PORT:8080}

app:
  name: ${APP_NAME}
  version: ${APP_VERSION}
  cors:
    enabled: ${CORS_ENABLED:false}
    allowed:
      credentials: ${CORS_ALLOWED_CREDENTIALS:false}
      origins: ${CORS_ALLOWED_ORIGINS:null}
      headers: ${CORS_ALLOWED_HEADERS:null}
      methods: ${CORS_ALLOWED_METHODS:null}
  totp:
    issuer: ${TOTP_ISSUER}
    digits: ${TOTP_DIGITS:8}
    ntp: ${TOTP_NTP}
    time:
      discrepancy: ${TOTP_TIME_DISCREPANCY:0}
      period: ${TOTP_TIME_PERIOD:0}
  radius:
    secret: ${RADIUS_SECRET}
    group: ${RADIUS_GROUP}
    nas-identifiers: ${RADIUS_NAS_IDENTIFIERS}
    nas-ips: ${RADIUS_NAS_IPS}
    nas-login: ${RADIUS_NAS_LOGIN}
  mail:
    template:
      qr-code: templates/email/qr-code.html
      notify-login: templates/email/notify-login.html
      notify-logged: templates/email/notify-logged.html
  geoip:
    database:
      path: ${GEOIP_DATABASE_PATH:/databases/GeoLite2-City.mmdb}
      url: ${GEOIP_DATABASE_URL:https://cdn.jsdelivr.net/npm/geolite2-city/GeoLite2-City.mmdb.gz}
      update:
        enabled: ${GEOIP_DATABASE_UPDATE_ENABLED:true}
        cron: ${GEOIP_DATABASE_UPDATE_CRON:0 0 2 * * *}